engineering_activities = [
    "Synergizing",
    "Innovating",
    "1:1-ing",
    "Meeting",
    "Planning",
    "Analyzing",
    "Circling back",
    "Closing the loop",
    "Dreaming",
    "Optimizing",
    "Evaluating",
    "Deciding",
    "Boot strapping",
    "Iterating",
    "Launching",
    "Thinking",
    "Brainstorming",
]


business_activities = [
    "Communicating",
    "Synergizing",
    "Innovating",
    "1:1-ing",
    "Meeting",
    "Greeting",
    "Planning",
    "Analyzing",
    "Circling back",
    "Closing the loop",
    "Dreaming",
    "Optimizing",
    "Process building",
    "Evaluating",
    "Deciding",
    "Investing",
    "Researching",
    "Flowing",
    "Thinking",
    "Brainstorming",
]

networking_activities = [
    "Communicating",
    "Meeting",
    "Greeting",
    "Recruiting",
    "Prospecting",
]
