placepicker:
  build: services/placepicker
  env_file: .env
  restart: always
jukebox:
  build: services/jukebox
  restart: always
scheduler:
  build: services/scheduler
  env_file: .env
  restart: always
alarm:
  build: services/alarm
  restart: always
tsp:
  build: services/tsp
  restart: always
selenium:
  image: selenium/standalone-firefox
  restart: always
eventbrowser:
  build: app/web_eventbrowser
  restart: always
eventdb:
  build: services/eventdb
  command: eventdb -db "postgres://postgres:postgres@postgres/postgres?sslmode=disable"
  links:
    - postgres
  restart: always
postgres:
  image: postgres:9.6
  restart: always
  environment:
    - POSTGRES_PASSWORD=postgres
  volumes:
    - /var/lib/postgresql/data:/var/lib/postgresql/data
frontend:
  build: services/frontend
  links:
    - tsp
    - alarm
    - scheduler
    - jukebox
    - placepicker
    - eventbrowser
    - eventdb
  volumes:
    - .caddy:/.caddy
  ports:
    - 80:80
    - 443:443
  restart: always
