placepicker:
  build: services/placepicker
  env_file: .env
  restart: always
jukebox:
  build: services/jukebox
  restart: always
scheduler:
  build: services/scheduler
  env_file: .env
  restart: always
alarm:
  build: services/alarm
  restart: always
tsp:
  build: services/tsp
  restart: always
selenium:
  image: selenium/standalone-firefox
  restart: always
eventbrowser:
  build: app/web_eventbrowser
  restart: always
frontend:
  build: services/frontend
  links:
    - tsp:tsp
    - alarm:alarm
    - scheduler:scheduler
    - jukebox:jukebox
    - placepicker:placepicker
    - eventbrowser:eventbrowser
  volumes:
    - .caddy:/.caddy
  ports:
    - 80:80
    - 443:443
  restart: always
