placepicker:
  build: services/placepicker
  env_file: .env
  ports:
    - 8001:5000
  restart: always
jukebox:
  build: services/jukebox
  ports:
    - 8002:8080
  restart: always
scheduler:
  build: services/scheduler
  env_file: .env
  ports:
    - 8003:5000
  restart: always
alarm:
  build: services/alarm
  ports:
    - 8004:8080
  restart: always
tsp:
  build: services/tsp
  ports:
    - 8005:8000
  restart: always
